### ISSUE TITLE
Tock Exception

### ISSUE THREAD

**Issue by ssosas** [linto-ai/linto-platform-stack#10]
Hi all,
I would like to share with you a crash that occurs when the tock session is not closed properly, I mean when you directly close the browser after working on tock instead of "disconnect button". This crash makes "down" other services on the stack like for exemple:
- linto-platform-admin
- linto-platform-bls
- linto-platform-overwatch
- linto-tock-mongo
- linto-tock-nlp-api
- linto-tock-nlu-web
- ....

After that, the only way to restart the stack correctly is to remove and restart all the stack by using the next command:
$ docker stack rm linto_stack && ./start.sh

Hope it will help you ;)

Here first lines of logs for tock-nlp-api docker service when the exception happens. Let me know if you would like to get more logs ;)

Cheers!

=====================================
 linto_stack_linto-tock-nlp-api.1.tj8gm0saluwx@libertad    | 2021-03-02T01:19:32.326 [cluster-ClusterId{value='603c6df4052b1c7a9d8cd156', description='null'}-linto-tock-mongo:27017] INFO  org.mongodb.driver.cluster - Exception in monitor thread while connecting to server linto-tock-mongo:27017
linto_stack_linto-tock-nlp-api.1.tj8gm0saluwx@libertad    | com.mongodb.MongoNodeIsRecoveringException: Command failed with error 11600 (InterruptedAtShutdown): 'interrupted at shutdown' on server linto-tock-mongo:27017. The full response is {"operationTime": {"$timestamp": {"t": 1614644323, "i": 1}}, "ok": 0.0, "errmsg": "interrupted at shutdown", "code": 11600, "codeName": "InterruptedAtShutdown", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1614644323, "i": 1}}, "signature": {"hash": {"$binary": "AAAAAAAAAAAAAAAAAAAAAAAAAAA=", "$type": "00"}, "keyId": {"$numberLong": "0"}}}}
linto_stack_linto-tock-nlp-api.1.tj8gm0saluwx@libertad    | 	at com.mongodb.internal.connection.ProtocolHelper.createSpecialException(ProtocolHelper.java:242)
linto_stack_linto-tock-nlp-api.1.tj8gm0saluwx@libertad    | 	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:171)
linto_stack_linto-tock-nlp-api.1.tj8gm0saluwx@libertad    | 	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:303)
linto_stack_linto-tock-nlp-api.1.tj8gm0saluwx@libertad    | 	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:259)
linto_stack_linto-tock-nlp-api.1.tj8gm0saluwx@libertad    | 	at com.mongodb.internal.connection.CommandHelper.sendAndReceive(CommandHelper.java:83)
linto_stack_linto-tock-nlp-api.1.tj8gm0saluwx@libertad    | 	at com.mongodb.internal.connection.CommandHelper.executeCommand(CommandHelper.java:38)
linto_stack_linto-tock-nlp-api.1.tj8gm0saluwx@libertad    | 	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:180)
....

**Comment by Houpert** [comment]
Hello,

We have never encounter that problem. Currently an old version of TOCK is used, we plan on the next release to update TOCK  (19.9.3 to 20.9.3 version). I hope this will fix the problem. 

If the problem persist after the update, I will try to see with the TOCK team.

**Comment by Houpert** [comment]
Hello,
Tock has been updated to the last version 20.9.3.
If you pull the last version and update the TOCK version could you told us if this fix the problem ?

**Comment by ssosas** [comment]
Hi all!
I did this update but the crash remains :(

The log is not exactly the same even if the service tock-nlp is the most verbose again:

**linto_stack_linto-tock-nlp-api**.1.osapa2a9ik8i@libertad    | 2021-04-29 17:34:05,445 ERROR [main] a.t.n.f.s.ConfigurationRepository: Command failed with error 10107 (NotMaster): 'not master' on server linto-tock-mongo:27017. The full response is {"operationTime": {"$timestamp": {"t": 1619710413, "i": 1}}, "ok": 0.0, "errmsg": "not master", "code": 10107, "codeName": "NotMaster", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1619710444, "i": 1}}, "signature": {"hash": {"$binary": {"base64": "AAAAAAAAAAAAAAAAAAAAAAAAAAA=", "subType": "00"}}, "keyId": 0}}}
linto_stack_linto-tock-nlp-api.1.osapa2a9ik8i@libertad    | com.mongodb.MongoNotPrimaryException: Command failed with error 10107 (NotMaster): 'not master' on server linto-tock-mongo:27017. The full response is {"operationTime": {"$timestamp": {"t": 1619710413, "i": 1}}, "ok": 0.0, "errmsg": "not master", "code": 10107, "codeName": "NotMaster", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1619710444, "i": 1}}, "signature": {"hash": {"$binary": {"base64": "AAAAAAAAAAAAAAAAAAAAAAAAAAA=", "subType": "00"}}, "keyId": 0}}}
linto_stack_linto-tock-nlp-api.1.osapa2a9ik8i@libertad    | 	at com.mongodb.internal.connection.ProtocolHelper.createSpecialException(ProtocolHelper.java:244)

Many thanks for your help!!

The whole file containing all logs is attached here!
[logs_stack_linto_03052021.txt](https://github.com/linto-ai/linto-platform-stack/files/6414287/logs_stack_linto_03052021.txt)
