### ISSUE TITLE
Context creation

### ISSUE THREAD

**Issue by jeanemvista** [linto-ai/linto-platform-stack#5]
In admin interface, I can't create a Context : 

<img width="1289" alt="Screenshot 2020-07-16 at 09 04 41" src="https://user-images.githubusercontent.com/36646779/87638043-6b96c280-c743-11ea-942f-a395de47f652.png">

**Comment by damienlaine** [comment]
The admin interface is currently broken as the specification of other services changed a lot.
We're working on it. Expect a functionnal version by September.
I'll keep you updated.

**Comment by damienlaine** [comment]
@jeanemvista : You might try using the stack with "latest-unstable" tag instead of "latest". This is still work in progress though.

**Comment by jeanemvista** [comment]
@damienlaine : I pull the repository and update my stack and I used latest-unstable tag.
But, now I have this problem when Linto-plateform-admin container start : 
```
Webserver started on port :  80
(node:520) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(Use 'node --trace-deprecation ...' to show where the warning was created)
Error: Cannot find module '/usr/src/app/linto-admin/webserver/model/mongodb/models/clients-static.js'
Require stack:
- /usr/src/app/linto-admin/webserver/lib/webserver/routes/api/clients/index.js
- /usr/src/app/linto-admin/webserver/lib/webserver/routes/routes.js
- /usr/src/app/linto-admin/webserver/lib/webserver/routes/index.js
- /usr/src/app/linto-admin/webserver/lib/webserver/index.js
- /usr/src/app/linto-admin/webserver/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/src/app/linto-admin/webserver/lib/webserver/routes/api/clients/index.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/linto-admin/webserver/lib/webserver/routes/api/clients/index.js',
    '/usr/src/app/linto-admin/webserver/lib/webserver/routes/routes.js',
    '/usr/src/app/linto-admin/webserver/lib/webserver/routes/index.js',
    '/usr/src/app/linto-admin/webserver/lib/webserver/index.js',
    '/usr/src/app/linto-admin/webserver/app.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! linto-admin@0.2.0 start: `NODE_ENV=production node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the linto-admin@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-19T05_33_45_094Z-debug.log
```

**Comment by rlopezdev** [comment]
Hi @jeanemvista, We're actually working on it and trying to deploy a new version. This error has been fixed but they are other issues that we are working on. 
Thanks for your feedbacks
